Add scholarship page-Complete
2110336-2565-2/Sec1_Group5_Schoolar pull request #102
Opened 2023-02-27 15:30 UTC by Nichapanit

มะเหมี่ยวฝาก test หน้า add-scholarship ทีจะ pr

2023-02-28 01:41 UTC, Nichapanit commented
แก้แล้วเหลือ 
- organization name ให้ไปดึงจาก database ตาม provider ที่ login อยู่ขณะนั้น + เป็นช่องที่แก้ไม่ได้ (เพราะตอนนี้ใน schema เก็บเป็น ObjectId ของ provider)

- ตอนนี้มี alert validate input แค่บาง field

- field ที่มี alert validation input เช่น Scholarship Nationใช้ validation จากใน formUtils ทำให้ alert ‘Target Nation is invalid’ แต่ label field ว่า ‘Scholarship Nation’

- ข้อมูลไม่ save ลง database

2023-02-28 03:38 UTC, Nichapanit commented
To Sasa
ทำ
- เปลี่ยนสี pinIcon -> pin : blue, not pin: grey
อยากให้เช็คว่า
- เปลี่ยนสีได้มั้ย
- ค่า active ตรงกับสีที่เปลี่ยนมั้ย (pin active=false: grey, pin active=true: blue)
- อยากเปลี่ยนสีที่ pin มั้ย

2023-02-28 04:24 UTC, NonRoute approved these changes

2023-02-28 06:16 UTC, mameowwy requested changes
- ยังไม่มี validate scholarship name, amount, quota
- alert required input ไม่เหมือนกับหน้าอื่น (หน้าอื่นจะขึ้นเป็นตัวหนังสือสีแดง if input is required)
- ยังไม่มี ui โชว์ตอน submit เสร็จว่า scholarship added successfully (or sth like that) เหมือนกับตอน register/login/logout (เปลี่ยน alert เป็น ui นี้)

2023-02-28 10:44 UTC, Nichapanit commented
แก้

- validate scholarship name, amount, quota แล้ว

- alert required input เป็นสีแดงแล้ว

- มี ui โชว์ตอน submit เสร็จว่า Add scholarship successfully!

2023-02-28 11:36 UTC, mameowwy requested changes
ตอนนี้ถ้าไม่ใส่ application deadline แล้ว submit จะ alert ทำให้ submit ไม่ได้ (จริงๆควรจะต้อง submit ได้)

2023-02-28 12:06 UTC, NonRoute approved these changes

2023-02-28 12:22 UTC, Nichapanit commented
แก้

- application deadline แล้ว submit ได้แล้วแม้ไม่ได้ใส่ค่า แต่ค่าที่ได้จะเป็นค่าวันที่ add scholarship แทน คือ กรอกวันที่ 28/02/2023 deadline = 28/02/2023 //ใน model เก็บค่าเป็น date เลย - ไม่ได้

อยากให้เช็คเพิ่ม

- ปุ่ม button หน้า add scholarship กับ edit acholarship ไม่เท่ากัน จะสรุปเป็นแบบไหนน

2023-02-28 17:27 UTC, Nichapanit commented
แก้

- ไม่ใส่ deadline value = null
- button เป็นแบบนี้เลย

2023-03-01 04:47 UTC, mameowwy approved these changes

2023-03-01 09:52 UTC, NonRoute approved these changes

2023-03-01 09:52 UTC, merged