Edit information
2110336-2565-2/Sec1_Group5_Schoolar pull request #97
Opened 2023-02-27 08:18 UTC by giftnichakul

Add client/components/Layout/FormEdit.js -> วาง component ตาม figma
Edit client/components/Layout/FormEditPvd.js -> แก้เป็น textfield ของ formComponentUtils, จัดให้ตรงตาม figma
Edit client/components/Layout/FormEditStd.js -> แก้เป็น textfield ของ formComponentUtils, จัดให้ตรงตาม figma
Edit client/components/Layout/Navbar.js -> เพิ่มให้เมื่ออยู่หน้า edit เมื่อกด edit อีกรอบหนเ้าจะ reload
Edit client/components/Layout/index.js -> ปรับ position ของ children ให้อยู่ center
Edit server/controllers/student.controller.js -> เพิ่มตัวแปรใน updateStudentInfo degree, program, gpax

2023-02-27 08:28 UTC, NonRoute requested changes

2023-02-27 08:28 UTC, NonRoute commented on client/components/Layout/FormEdit.js
> +const FormSecondary = ({ header, form }) => {
- เปลี่ยนชื่อ function ให้ตรงตามชื่อไฟล์
- ถ้าเป็นไปได้ให้ใช้ formPrimary, formSecondary ที่สร้างไว้แล้ว โดยสามารถปรับเปลี่ยนเพื่อให้รองรับกับ page ที่จะสร้างได้

2023-02-27 15:22 UTC, giftnichakul commented
commit 6:
src/pages/profile -> Use FormSecondary instead
components/Layout/FormEditPvd -> delete creditCardNumber, Change position to be similar in figma
components/Layout/FormEditStd -> Change position to be similar in figma, Fix bug when change SelectComponent and the birthdate will not change to Today
utils/formComponentUtils -> change values to be controlled component

2023-02-28 15:42 UTC, NonRoute commented on client/components/Layout/FormEditStd.js
> +								values={birthdate}
ไม่แน่ใจว่าตรงนี้ไม่ต้องใส่ props เพิ่ม ทำเหมือนหน้า student register ได้ไหมนะ หรือว่าเกิดปัญหาอะไรไหม

2023-02-28 15:50 UTC, giftnichakul commented
-add snackbar in EditPvd and EditStd
-change providerName to organizationName

2023-02-28 16:40 UTC, mameowwy approved these changes

2023-02-28 16:55 UTC, NonRoute approved these changes

2023-02-28 17:06 UTC, merged